version: '3.8'

services:
  app:
    build:
      # https://stackoverflow.com/questions/24537340/docker-adding-a-file-from-a-parent-directory
      context: .././
      dockerfile: ./.devcontainer/codespaces.dockerfile
    volumes:
      - ..:/workspaces/funct:cached
    # Overrides docker COMMAND so doesn't shut down when startup ends .
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: host
